services:
  api:
    build: .
    environment:
      - PASSWORD_SALT=12
      - POSTGRES_PASS=12345678
      - PGHOST=postgres
      - MAX_LATE_COUNT=5
      - BAN_DURATION_MS=2629746000
    ports:
      - 7005:3000
  postgres:
    build: ./postgres
    environment:
      - POSTGRES_PASSWORD=12345678
