services:
  api:
    build: .
    environment:
      - PASSWORD_SALT=12
      - POSTGRES_PASS=12345678
      - PGHOST=postgres
    ports:
      - 3000:3000
  postgres:
    build: ./postgres
    environment:
      - POSTGRES_PASSWORD=12345678
